# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: 'en-US'
early_access: true
reviews:
  profile: 'chill'
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  review_status: true
  poem: false
  collapse_walkthrough: false
  sequence_diagrams: true
  changed_files_summary: true
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
chat:
  auto_reply: true
knowledge_base:
  opt_out: true
  learnings:
    scope: auto
enable_free_tier: true
